server:
  port: 8001

spring:
  application:
    name: provider-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/as_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group
    nacos:
      discovery:
        server-addr: 192.168.0.101:1111
    sentinel:
      transport:
        dashboard: 192.168.0.101:8080
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.0.101:1111
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
mybatis:
  # mapper
  mapper-locations: classpath:mapper/*.xml
  # entity别名类所在包
  type-aliases-package: com.as.seckill.entity