server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 16MB
  application:
    name: provider-goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/as_seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group
    nacos:
      discovery:
        server-addr: 192.168.0.101:3333
mybatis:
  # mapper
  mapper-locations: classpath:mapper/*.xml